filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "flight-tracker-logs-%{+yyyy.MM.dd}"

setup.template.name: "flight-tracker"
setup.template.pattern: "flight-tracker-logs-*"
setup.template.enabled: true

logging.level: info