global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    
  - job_name: 'flight-data-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'
    
  - job_name: 'websocket-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/metrics'

  - job_name: 'flink-cluster'
    static_configs:
      - targets: ['host.docker.internal:30249']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['host.docker.internal:9308']
    metrics_path: '/metrics'
    scrape_interval: 30s