global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    
  - job_name: 'flight-data-service'
    static_configs:
      - targets: ['flight-data-service:8081']
    metrics_path: '/metrics'
    
  - job_name: 'websocket-service'
    static_configs:
      - targets: ['websocket-service:8082']
    metrics_path: '/metrics'