# main docker-compose.yml

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - real-time-dashboard_default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.backend
    depends_on:
      - redis
    networks:
      - real-time-dashboard_default
      - kafka-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    networks:
      - real-time-dashboard_default

networks:
  real-time-dashboard_default:
    driver: bridge
  kafka-network:
    external: true
    name: kafka_kafka-network

volumes:
  redis_data:
