# docker-compose.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPEN_SKY_API_URL=https://opensky-network.org/api/states/all
      - ALLOWED_ORIGINS=http://localhost:3000
      - LOG_LEVEL=INFO # <--- NEW: Set this to INFO, DEBUG, WARN, ERROR, or FATAL
    networks:
      - real-time-dashboard_default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://backend:8080/ws
    depends_on:
      - backend
    networks:
      - real-time-dashboard_default

networks:
  real-time-dashboard_default:
    driver: bridge
