version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - flight-tracker

  flight-data-service:
    build:
      context: .
      dockerfile: ./services/flight-data-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - FETCH_INTERVAL=15s
      - MAX_CONNECTIONS=1000
    depends_on:
      - redis
    networks:
      - flight-tracker
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  websocket-service:
    build:
      context: .
      dockerfile: ./services/websocket-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MAX_CONNECTIONS=1000
    networks:
      - flight-tracker
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - RATE_LIMIT_PER_IP=5
    depends_on:
      flight-data-service:
        condition: service_healthy
      websocket-service:
        condition: service_healthy
    networks:
      - flight-tracker
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mock-data-service:
    build:
      context: .
      dockerfile: ./services/mock-data-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=flights
      - FETCH_INTERVAL=15s
    depends_on:
      - kafka
    networks:
      - flight-tracker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8082/ws
    depends_on:
      - api-gateway
    networks:
      - flight-tracker

networks:
  flight-tracker:
    driver: bridge