# main docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPEN_SKY_API_URL=https://opensky-network.org/api/states/all
      - ALLOWED_ORIGINS=http://localhost:3000
      - LOG_LEVEL=INFO
      - KAFKA_BROKER_ADDRESS=broker:29092
      - KAFKA_TOPIC=flights
      - KAFKA_GROUP_ID=flight-websocket-group
      - USE_MOCK_DATA=true
    networks:
      - real-time-dashboard_default
      - kafka-network # Connect to the Kafka network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # CHANGE THIS LINE:
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8080/ws
    depends_on:
      - backend
    networks:
      - real-time-dashboard_default

networks:
  real-time-dashboard_default:
    driver: bridge
  kafka-network: # Refer to the external network by the name it was actually created with
    external: true
    name: kafka_kafka-network
