apiVersion: v1
kind: Namespace
metadata:
  name: flight-tracker
  labels:
    name: flight-tracker
    app.kubernetes.io/name: flight-tracker
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: flight-tracker-quota
  namespace: flight-tracker
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: flight-tracker-limits
  namespace: flight-tracker
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container