apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: flight-events
  namespace: flight-tracker
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 86400000
    compression.type: snappy
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: flight-alerts
  namespace: flight-tracker
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 86400000
    compression.type: snappy