apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flight-tracker-flink
  namespace: stream-analytics
spec:
  image: flink:1.18-scala_2.12-java11
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    state.backend: filesystem
    execution.checkpointing.interval: 60s
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: "2"
    restart-strategy.fixed-delay.delay: 10s
    metrics.reporters: prom
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.host: 0.0.0.0
    metrics.reporter.prom.port: "9249"
  serviceAccount: stream-analytics
  jobManager:
    resource:
      memory: "512m"
      cpu: 0.5
    replicas: 1
    ports:
      - name: ui
        containerPort: 8081
      - name: metrics
        containerPort: 9249
  taskManager:
    resource:
      memory: "512m"
      cpu: 0.5
    replicas: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - mountPath: /flink-data
              name: flink-data
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "flight-tracker-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
      volumes:
        - name: flink-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flight-tracker-flink-ui
  namespace: flink
spec:
  type: NodePort
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: metrics
      port: 9249
      targetPort: 9249
      nodePort: 30249
  selector:
    app: flight-tracker-flink
    component: jobmanager