apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinot-controller
  namespace: pinot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinot-controller
  template:
    metadata:
      labels:
        app: pinot-controller
    spec:
      containers:
      - name: pinot-controller
        image: apachepinot/pinot:1.0.0
        args:
          - StartController
          - -zkAddress
          - pinot-zookeeper:2181
        ports:
        - containerPort: 9000
        - containerPort: 8000
        env:
        - name: JAVA_OPTS
          value: "-Xms512M -Xmx1G"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinot-broker
  namespace: pinot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinot-broker
  template:
    metadata:
      labels:
        app: pinot-broker
    spec:
      containers:
      - name: pinot-broker
        image: apachepinot/pinot:1.0.0
        args:
          - StartBroker
          - -zkAddress
          - pinot-zookeeper:2181
        ports:
        - containerPort: 8099
        env:
        - name: JAVA_OPTS
          value: "-Xms512M -Xmx1G"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinot-server
  namespace: pinot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinot-server
  template:
    metadata:
      labels:
        app: pinot-server
    spec:
      containers:
      - name: pinot-server
        image: apachepinot/pinot:1.0.0
        args:
          - StartServer
          - -zkAddress
          - pinot-zookeeper:2181
        ports:
        - containerPort: 8098
        - containerPort: 8090
        env:
        - name: JAVA_OPTS
          value: "-Xms512M -Xmx1G"
        volumeMounts:
        - name: pinot-data
          mountPath: /opt/pinot/data
      volumes:
      - name: pinot-data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinot-zookeeper
  namespace: pinot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinot-zookeeper
  template:
    metadata:
      labels:
        app: pinot-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.8
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_SERVERS
          value: "server.1=0.0.0.0:2888:3888;2181"
        volumeMounts:
        - name: zk-data
          mountPath: /data
      volumes:
      - name: zk-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pinot-controller
  namespace: pinot
spec:
  type: NodePort
  ports:
  - name: controller
    port: 9000
    targetPort: 9000
    nodePort: 30900
  - name: admin
    port: 8000
    targetPort: 8000
    nodePort: 30800
  selector:
    app: pinot-controller
---
apiVersion: v1
kind: Service
metadata:
  name: pinot-broker
  namespace: pinot
spec:
  type: NodePort
  ports:
  - name: broker
    port: 8099
    targetPort: 8099
    nodePort: 30099
  selector:
    app: pinot-broker
---
apiVersion: v1
kind: Service
metadata:
  name: pinot-server
  namespace: pinot
spec:
  ports:
  - name: server
    port: 8098
    targetPort: 8098
  - name: admin
    port: 8090
    targetPort: 8090
  selector:
    app: pinot-server
---
apiVersion: v1
kind: Service
metadata:
  name: pinot-zookeeper
  namespace: pinot
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  - name: follower
    port: 2888
    targetPort: 2888
  - name: election
    port: 3888
    targetPort: 3888
  selector:
    app: pinot-zookeeper