kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: flight-tracker
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 9092
    hostPort: 9092
    protocol: TCP
  - containerPort: 8081
    hostPort: 8081
    protocol: TCP